# Generated by Django 5.1.6 on 2025-03-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newapp', '0002_auto_20250327_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransplantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_object_id', models.PositiveIntegerField()),
                ('organ', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('donor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.recipientorganneeded')),
            ],
        ),
        migrations.DeleteModel(
            name='TransplantMatchRecord',
        ),
    ]
