# Generated by Django 5.1.6 on 2025-03-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_transplantallocation_delete_transplantmatchrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='newapp.donordetails')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='newapp.recipient')),
            ],
        ),
    ]
