# Generated by Django 5.1.6 on 2025-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_organmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingdonationdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
