# Generated by Django 5.1.6 on 2025-03-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_livingdonationdocument_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceaseddonationfile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
