# Generated by Django 5.1.6 on 2025-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_deceaseddonationfile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
