# Generated by Django 5.1.6 on 2025-03-27 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_medicaldocument_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceaseddonation',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='livingorgandonation',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
