# Generated by Django 5.1.6 on 2025-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_transplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transplant',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
