# Generated by Django 5.1.6 on 2025-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_transplant_attended_transplant_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplant',
            name='living_donation',
            field=models.BooleanField(default=False),
        ),
    ]
