# Generated by Django 5.1.6 on 2025-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_transplant_living_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transplant',
            old_name='attended',
            new_name='donor_attended',
        ),
        migrations.AddField(
            model_name='transplant',
            name='recipient_attended',
            field=models.BooleanField(default=False),
        ),
    ]
