# Generated by Django 5.1.6 on 2025-03-31 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_rename_attended_transplant_donor_attended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('Transplant Success Rate', 'Transplant Success Rate'), ('Donor Trends', 'Donor Trends'), ('Hospital Performance', 'Hospital Performance')], max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
