# Generated by Django 5.1.6 on 2025-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceaseddonationfile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livingdonationdocument',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
