# Generated by Django 5.1.6 on 2025-04-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.hospitaldetail'),
        ),
    ]
